### ISSUE TITLE
I am not too sure what to do.

### ISSUE THREAD

**Issue by vass7** [JDHatten/Switch-Save-Game-Transfer#4]
Sooo.. im not the best at code stuff. Im trying to move my zelda TOTK game save files from Ryujinx to Yuzu.

I atempted to edit the code and repace it with my ID codes. But i am not entierly sure what my codes are and where to find them.

So when i paste the code into my CMD it just closes and nothing is changing. Deffinetly not a fault in your code, im just stupid and don't understand this stuff..

**Comment by JDHatten** [comment]
Hi Vass7,

OK try starting over with a new copy of the code with no changes yet made (redownload).  

Now in Windows Explorer, go to “C:\Users\{YourUserName}\AppData\Roaming\yuzu\nand\user\save\0000000000000000\”
Here you should see one or more yuzu user account folders, ignore the “00000000000000000000000000000000” folder and pick one of the others with a mixture of numbers and letters. You may explore the folder to confirm your save files are really there. Then copy that folder name, it should look something like “2608X194X2FD3B25D1F3G29DD57B774E”. 

Now back in the “.cmd file”, find and replace {your yuzu user id} with that folder name/ID (no brackets).

Next open Ryujinx and right click your game (TotK) and select “Open User Save Directory”. You should see a path similar to this “C:\Users\{YourUserName}\AppData\Roaming\Ryujinx\bis\user\save\000000000000001c\0”. The number “000000000000001c” is what you want to copy, but you only need to remember the last two digits “1c” in this example.  

Now back in the “.cmd file”, replace “{xx}” with “1c” under the “The Legend of Zelda: Tears of the Kingdom” line.

Lastly save the file and run it.  Assuming no mistakes were made it should work. Let me know how it goes.

**Comment by vass7** [comment]
Yes! it worked. Thank you!

**Comment by JDHatten** [comment]
You're welcome, have fun.
